---
title: J++ Style Guide
email: contact@jplusplus.org
description: > # this means to ignore newlines until "baseurl:"
  The J++ Style Guide and Coding practices
baseurl: ""  # the subpath of your site, e.g. /blog
url: "http://style.jplusplus.pt"  # the base hostname & protocol for your site
twitter_username: jplusplus_
github_username: jplusplus

# Build settings
markdown: kramdown
